name: Python application

on: [push]

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.13t', '3.14t', 'pypy3.10']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            python-version: '3.10'
          # free-threaded builds only on ubuntu for now
          - os: macOS-latest
            python-version: '3.13t'
          - os: macOS-latest
            python-version: '3.14t'
          - os: windows-latest
            python-version: '3.13t'
          - os: windows-latest
            python-version: '3.14t'
      fail-fast: false
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements-test.txt
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        coverage run -m pytest
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Upload coverage
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          # This will only work if we also send a "done" event after the
          # whole job is finished.
          # See: https://docs.coveralls.io/parallel-build-webhook
          #COVERALLS_PARALLEL: "true"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CI_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      if: matrix.os == 'ubuntu-latest'
      run: |
        coveralls --service=github
